const GET_APIFETCH = 'GET_APIFETCH';
const DATA_REQUESTED = 'DATA_REQUESTED';
const DATA_LOADED = 'DATA_LOADED';
const TOOGLE_LATERALMENU = 'TOOGLE_LATERALMENU';
const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';

export {
    GET_APIFETCH, DATA_REQUESTED, DATA_LOADED, TOOGLE_LATERALMENU,
    SHOW_NOTIFICATION,
};